name: C++ MSBuild 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Cmake Configure
      run: cmake -B ${{github.workspace}}/build
    
    - name: Build-Debug
      run: cmake --build ${{github.workspace}}/build --config debug

    - name: Build-Release
      run: cmake --build ${{github.workspace}}/build --config release
