name: C++ Premake vcpkg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: vcpkg build
      id: vcpkg
      uses: johnwason/vcpkg-action@v6
      with:
      manifest-dir: ${{ github.workspace }} 
      triplet: x64-windows-release
      token: ${{ github.token }}
      github-binarycache: true


    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Generate VS solution 
      run: ./premake5.exe vs2022 
    
    - name: Build-Debug
      run: msbuild /p:VcpkgEnableManifest=true voxel-engine.sln /p:Configuration=Debug

    - name: Build-Release
      run: msbuild /p:VcpkgEnableManifest=true voxel-engine.sln /p:Configuration=Release
