name: C++ MSBuild 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Generate VS solution file
      run: ./premake5.exe vs2022
    
    - name: Build-Debug
      run: msbuild voxel-engine.sln /p:Configuration=Debug

    - name: Build-Release
      run: msbuild voxel-engine.sln /p:Configuration=Release
